<?php
/*
Created By: Noah O'Grady
KUID: 3071519
Last Edited: 5/10/24
*/


//Visualize logic takes exercise from progress.php and generates a line graph populated by user information
//Individual lines represent different rep ranges for the given exercise
//The x-axis is the date the exercise was recorded, and the y-axis is the amount of weight used
//The graphs are generated by CanvasJS

//start session and include database connection
include "db_conn.php";
session_start();

//make sure user is logged in
if (isset($_SESSION['user_id']) && isset($_SESSION['username'])) {
    
    //get user id and exercise from session. User id is set by login.php and selected_exercise is set by progress.php
    $user_id = $_SESSION['user_id'];
    $exercise = $_SESSION['selected_exercise'];

    //get distinct rep ranges for the given exercise performed by the loggin in user
    $sql = "SELECT DISTINCT reps FROM sets WHERE sets.user_id = '$user_id' AND sets.exercise = '$exercise'";
    $result = mysqli_query($conn, $sql);

    $data = array();

    //for each rep range, query the database to get the max weight used for a given rep range on a given day, and create data points based on the result
    while ($row = mysqli_fetch_array($result)) {
        $reps = $row['reps'];
        $sql = "SELECT workout_date, MAX(weight) FROM sets, workouts WHERE workouts.workout_id = sets.workout_id AND sets.user_id = '$user_id' AND exercise = '$exercise' AND reps = '$reps' GROUP BY workout_date ORDER BY workout_date";
        $result_sub = mysqli_query($conn, $sql);
        $sub_data = array();
        while ($sub_row = mysqli_fetch_array($result_sub)) {
            $sub_data[] = array(
                "label" => " ",
                "y" => $sub_row["MAX(weight)"]
            );
        }
        $data[] = array(
            "type" => "line",
            "name" => "$reps Reps",
            "showInLegend" => true,
            "willReadFrequently" => true,
            "dataPoints" => $sub_data
        );
    }
    $json_data = json_encode($data);

    //Query the database for the absolute max weight performed for the given exercise. This will be used for calculating recommended rep ranges for gaining strength
    $sql2 = "SELECT MAX(weight) FROM (SELECT weight FROM sets WHERE sets.user_id = '$user_id' AND sets.exercise = '$exercise') AS sub";
    $result2 = mysqli_query($conn, $sql2);
    $max_weight = mysqli_fetch_array($result2)['MAX(weight)']
?>
<!DOCTYPE HTML>
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.min.js"></script>
<script>
//Create a canvas JS chart with user and exercise information
$(document).ready(function () {
    var chart = new CanvasJS.Chart("chartContainer", {
        title: {
            text: ""
        },
        axisY: {
            title: "Weight"
        },
        data: <?php echo json_encode($data, JSON_NUMERIC_CHECK); ?>
    });
    chart.render();
});
</script>
</head>
<body>
<h1><?php echo ucfirst($exercise); ?></h1>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<div class = 'container'>
    <div class = 'content'>
        <!--Suggested training table is populated based on percentages of the users absolute max. This is based on the Smolov Jr strength training plan that is used by many powerlifters -->
        <h1>Suggested Training</h1>
        <table border="1">
            <tr>
                <th>Week</th><th>Day</th><th>Lift</th><th>Sets</th><th>Reps</th><th>Weight</th>
            </tr>
            <tr>
                <td>1</td><td>1</td><td>1</td><td>6</td><td>6</td><td><?php echo round(((0.7) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>1</td><td>2</td><td>1</td><td>7</td><td>5</td><td><?php echo round(((0.75) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>1</td><td>3</td><td>1</td><td>8</td><td>4</td><td><?php echo round(((0.8) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>1</td><td>4</td><td>1</td><td>10</td><td>3</td><td><?php echo round(((0.85) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>2</td><td>1</td><td>1</td><td>6</td><td>6</td><td><?php echo round(((0.75) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>2</td><td>2</td><td>1</td><td>7</td><td>5</td><td><?php echo round(((0.8) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>2</td><td>3</td><td>1</td><td>8</td><td>4</td><td><?php echo round(((0.85) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>2</td><td>4</td><td>1</td><td>10</td><td>3</td><td><?php echo round(((0.9) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>3</td><td>1</td><td>1</td><td>6</td><td>6</td><td><?php echo round(((0.8) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>3</td><td>2</td><td>1</td><td>7</td><td>5</td><td><?php echo round(((0.85) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>3</td><td>3</td><td>1</td><td>8</td><td>4</td><td><?php echo round(((0.9) * $max_weight)/5) * 5;?></td>
            </tr>
            <tr>
                <td>3</td><td>4</td><td>1</td><td>10</td><td>3</td><td><?php echo round(((0.95) * $max_weight)/5) * 5;?></td>
            </tr>
        </table>
        <!--Provide option for user to go back home -->
        <a href="home.php" class="link">Back To Home</a>
    </div>
</div>
</body>
</html>
<?php
//If user is not logged in, redirect them to login page
} else {
    header("Location: index.php");
    exit();
}
?>